### ISSUE TITLE
Error on new timer creater

### ISSUE THREAD

**Issue by MaksymSemenykhin** [titivermeesch/CommandTimer#18]
[12:22:17] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CommandTimer v2.4.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[server.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[server.jar:git-Spigot-093165$        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-093165d-ba575a5]        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [server.jar:git-Spigot-093165d-ba575a5]        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [server.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [server.jar:git-Spigot-093165d-ba575a$        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [server.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at me.playbosswar.com.GUIHandler.createCommandsGUI(GUIHandler.java:221) ~[?:?]
        at me.playbosswar.com.GUIListeners.mainGUI(GUIListeners.java:498) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-093165d-ba575a5]
        ... 17 more

**Comment by MaksymSemenykhin** [comment]
my config:
```
#GENERAL
timeonload: true

settings:
  tasks:
    '1':
      commands:
        - say This message will only show up at a specific time.
      onhour: true
      time: '13:49'
      seconds: 60
      onload: false
      gender: 'console'
    '2':
      commands:
        - say This message appears every 10 seconds with a chance of 50%
      onhour: false
      time:
        - '13:49'
      seconds: 10
      onload: false
      gender: 'console'
      useRandom: true
      random: 0.5
```
